### PR TITLE
Fix building on newer versions of Clang

### LINKED ISSUE #360: Cannot build on macOS
I'm following the instructions in the readme for macOS and I get the following error about a redundant semicolon in glm:

```
[  2%] Built target dbopl
[  6%] Built target entityx
[  8%] Built target glad
[ 10%] Built target speex_resampler
[ 10%] Building CXX object src/CMakeFiles/rigel_core.dir/engine/debugging_system.cpp.o
In file included from /Users/kylefalconer/sources/RigelEngine/src/engine/debugging_system.cpp:17:
In file included from /Users/kylefalconer/sources/RigelEngine/src/engine/debugging_system.hpp:22:
In file included from /Users/kylefalconer/sources/RigelEngine/src/engine/renderer.hpp:24:
In file included from /Users/kylefalconer/sources/RigelEngine/src/engine/shader.hpp:23:
In file included from /Users/kylefalconer/sources/RigelEngine/3rd_party/glm/glm/gtc/type_ptr.hpp:37:
In file included from /Users/kylefalconer/sources/RigelEngine/3rd_party/glm/glm/gtc/../gtc/quaternion.hpp:18:
In file included from /Users/kylefalconer/sources/RigelEngine/3rd_party/glm/glm/gtc/../gtc/matrix_transform.hpp:24:
In file included from /Users/kylefalconer/sources/RigelEngine/3rd_party/glm/glm/gtc/../mat4x4.hpp:5:
In file included from /Users/kylefalconer/sources/RigelEngine/3rd_party/glm/glm/gtc/.././ext/matrix_double4x4.hpp:5:
In file included from /Users/kylefalconer/sources/RigelEngine/3rd_party/glm/glm/gtc/../ext/../detail/type_mat4x4.hpp:188:
In file included from /Users/kylefalconer/sources/RigelEngine/3rd_party/glm/glm/gtc/../ext/../detail/type_mat4x4.inl:1:
In file included from /Users/kylefalconer/sources/RigelEngine/3rd_party/glm/glm/gtc/../ext/../detail/../matrix.hpp:161:
In file included from /Users/kylefalconer/sources/RigelEngine/3rd_party/glm/glm/gtc/../detail/func_matrix.inl:1:
In file included from /Users/kylefalconer/sources/RigelEngine/3rd_party/glm/glm/gtc/../ext/../detail/../geometric.hpp:116:
In file included from /Users/kylefalconer/sources/RigelEngine/3rd_party/glm/glm/gtc/../detail/func_geometric.inl:2:
In file included from /Users/kylefalconer/sources/RigelEngine/3rd_party/glm/glm/gtc/../ext/../detail/../common.hpp:532:
In file included from /Users/kylefalconer/sources/RigelEngine/3rd_party/glm/glm/gtc/../detail/func_common.inl:785:
In file included from /Users/kylefalconer/sources/RigelEngine/3rd_party/glm/glm/gtc/../ext/../detail/func_common_simd.inl:6:
/Users/kylefalconer/sources/RigelEngine/3rd_party/glm/glm/gtc/../ext/../detail/../simd/common.h:106:45: error: empty expression statement
      has no effect; remove unnecessary ';' to silence this warning [-Werror,-Wextra-semi-stmt]
        glm_vec4 const or0 = _mm_or_ps(and0, and1);;
                                                   ^
1 error generated.
make[2]: *** [src/CMakeFiles/rigel_core.dir/engine/debugging_system.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/rigel_core.dir/all] Error 2
make: *** [all] Error 2
```

Once I modify the glm code to fix the issue, I get a new error:

```
...
[ 49%] Building CXX object src/CMakeFiles/rigel_core.dir/game_logic/game_world.cpp.o
In file included from /Users/kylefalconer/sources/RigelEngine/src/game_logic/game_world.cpp:28:
In file included from /Users/kylefalconer/sources/RigelEngine/src/loader/resource_loader.hpp:21:
/Users/kylefalconer/sources/RigelEngine/src/data/movie.hpp:27:3: error: explicitly defaulted default constructor is implicitly deleted
      [-Werror,-Wdefaulted-function-deleted]
  MovieFrame() = default;
  ^
/Users/kylefalconer/sources/RigelEngine/src/data/movie.hpp:34:9: note: default constructor of 'MovieFrame' is implicitly deleted because
      field 'mReplacementImage' has no default constructor
  Image mReplacementImage;
        ^
1 error generated.
make[2]: *** [src/CMakeFiles/rigel_core.dir/game_logic/game_world.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/rigel_core.dir/all] Error 2
make: *** [all] Error 2
```

### PR DESCRIPTION
**Pull request by lethal-guitar**
Clang 8 introduces a few new warnings which we need to ignore/fix.

Fixes #360

### CODE REVIEW

**Comment by lethal-guitar** [comment]
@avioli @Kyle-Falconer could you check if this fixes the build for you as well? Thanks!

File: src/data/movie.hpp [hunk 1]
```diff
@@ -24,7 +24,6 @@
 namespace rigel { namespace data {
 
 struct MovieFrame {
-  MovieFrame() = default;
```
Comment (Kyle-Falconer) [inline src/data/movie.hpp]: This works, though the way I fixed it was to add the default constructor to image.hpp:

```
class Image {
public:
  Image();
  Image(PixelBuffer&& pixels, std::size_t width, std::size_t height);
  Image(const PixelBuffer& pixels, std::size_t width, std::size_t height);
  Image(std::size_t width, std::size_t height);
```

(I'm no cpp guy though, so I'll defer to you; just wanted to point out how I fixed it)
